### ISSUE TITLE
OAK diff does not work

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/rppr_stats#1]
Reproduce:

1. clone repo
2. run `make make p1-rppr-x -B`

```
(grh) (grainyhead) ➜  rppr_stats git:(main) ✗ runoak -i simpleobo:ontologies/mondo_2023-06-01.obo diff -X simpleobo:ontologies/mondo_2024-03-04.obo --statistics -o stats/mondo_diff.txt.yaml
Traceback (most recent call last):
  File "/Users/matentzn/.pyenv/versions/3.11.7/envs/grainyhead/bin/runoak", line 3, in <module>
    from oaklib.cli import main
  File "/Users/matentzn/ws/ontology-access-kit/src/oaklib/__init__.py", line 10, in <module>
    from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matentzn/ws/ontology-access-kit/src/oaklib/selector.py", line 15, in <module>
    from oaklib.implementations import GildaImplementation
  File "/Users/matentzn/ws/ontology-access-kit/src/oaklib/implementations/__init__.py", line 19, in <module>
    from oaklib.implementations.llm_implementation import LLMImplementation
  File "/Users/matentzn/ws/ontology-access-kit/src/oaklib/implementations/llm_implementation.py", line 11, in <module>
    from tenacity import (
ModuleNotFoundError: No module named 'tenacity'
(grh) (grainyhead) ➜  rppr_stats git:(main) ✗ pip list | grep oak
oaklib                     0.5.32
(grh) (grainyhead) ➜  rppr_stats git:(main) ✗ 
```

**Comment by hrshdhgd** [comment]
#2
